 CREATE TABLE persons (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name TEXT,
    year TEXT,
    experience TEXT,
    availability TEXT);
    
INSERT INTO persons (
    name, 
    year, 
    experience, 
    availability
    )
    
VALUES

("Henoc Codjie", "Junior", "Expert", "Friday, Saturday, Sunday"),
('Jay Elara', 'Freshman', 'Novice', 'Monday, Wednesday, Friday'),
('Taina Mane', 'Senior', 'Beginner', 'Saturday, Friday, Thursday'),
('Gerald Stoyanka', 'Sophomore','Novice', 'Wednesday, Saturday, Sunday'),
('Tilde Caren', 'Sophomore',"Expert", 'Thursday, Wednesday, Monday'),
('Jerry Florencia', 'Sophomore',"Expert", 'Thursday, Friday, Sunday'),
('Conner Vital', 'Senior',"Expert", 'Wednesday, Tuesday, Sunday'),
('Jessie Barra', 'Freshman','Beginner', 'Saturday, Friday, Sunday'),
('Matthew Mick', 'Junior','Novice', 'Monday, Sunday, Tuesday'),
('Hussein Rain', 'Freshman','Beginner', 'Monday Wednesday, Friday'),
('Fenton Horace', 'Freshman',"Expert", 'Friday, Saturday, Sunday'),
('Tivadar Matilde', 'Senior','Novice', 'Tuesday, Wednesday, Monday'),
('Nieve Taavi', 'Freshman',"Expert", 'Friday, Wednesday, Monday'),
('Nermin Yemima', 'Sophomore','Beginner', 'Tuesday, Thursday, Friday'),
('Sultana Sasha', 'Sophomore','Novice', 'Monday, Thursday, Friday'),
('Amondi Genevieve', 'Freshman','Beginner', 'Friday, Thursday, Sunday'),
('Keitha Naime', 'Sophomore',"Expert", 'Tuesday, Saturday, Friday'),
('Walter Sabina', 'Sophomore','Novice', 'Saturday, Thursday, Tuesday'),
('Mitsuaki Aisha', 'Sophomore','Novice', 'Tuesday, Saturday, Friday'),
('Fidan Tereza', 'Senior',"Expert", 'Saturday, Thursday, Friday'),
('Ali Vinka', 'Freshman','Novice', 'Tuesday, Saturday, Thursday'),
('Jill Nikodim', 'Freshman',"Expert", 'Saturday, Friday, Thursday'),
('Elazar Silvio', 'Sophomore','Novice', 'Friday, Sunday, Saturday'),
('Rabiu Cerise', 'Freshman','Novice', 'Monday Wednesday, Friday'),
('Vittorio Harel', 'Junior',"Expert", 'Friday, Wednesday, Saturday'),
('Alex Holland', 'Junior','Beginner', 'Wednesday, Saturday, Sunday'),
('Nikolas Cy', 'Senior',	"Expert", 'Friday, Monday, Saturday'),
('Csaba Katalin', 'Sophomore',"Expert", 'Saturday, Thursday, Friday'),
('Jessie', 'Senior','Beginner', 'Saturday, Friday, Monday'),
('Annika Idalia', 'Freshman',"Expert", 'Monday, Saturday, Friday'),
('Paul Aleks', 'Junior','Beginner', 'Saturday, Friday, Monday'),
('Megan Shaeffer', 'Junior','Beginner', 'Monday, Tuesday, Friday'),
('Kevin Chiran', 'Sophomore','Novice', 'Monday, Sunday, Friday'),
('Sverre Winton', 'Senior',"Expert", 'Friday, Saturday, Sunday'),
('Tahir Ogechi', 'Senior','Novice', 'Monday Wednesday, Friday'),
('Elma Eliza', 'Sophomore','Beginner', 'Friday, Tuesday, Sunday'),
('Drorit Viktoria', 'Freshman','Beginner', 'Saturday, Friday, Thursday'),
('Yumi Ayesha', 'Sophomore','Beginner', 'Saturday, Thursday, Friday'),
('Nessa Gratien', 'Freshman','Novice', 'Tuesday, Saturday, Sunday'),
('Fannar Ankica', 'Sophomore',"Expert", 'Thursday, Friday, Sunday'),
('Yamileth Chance', 'Sophomore','Novice', 'Tuesday, Saturday, Sunday'),
('Aron Plamen', 'Sophomore','Novice', 'Tuesday, Sunday, Friday'),
('Jacob Mellan', 'Freshman',"Expert", 'Thursday, Wednesday, Monday'),
('Elin Maile', 'Junior','Novice', 'Tuesday, Friday, Saturday'),
('Mattis Anh', 'Senior','Novice', 'Wednesday, Saturday, Sunday'),
('Montana Aleida', 'Junior','Novice', 'Friday, Thursday, Sunday'),
('Lysette Raghnaid', 'Freshman','Novice', 'Thursday, Saturday, Friday'),
('Robert Rita', 'Junior','Beginner', 'Friday, Thursday, Sunday'),
('Alex Garris', 'Sophomore','Novice', 'Thursday, Friday, Sunday'),
('Michala Raynard', 'Senior',"Expert", 'Wednesday, Thursday, Sunday'),
('Ji-Hoon Zlata', 'Sophomore','Novice', 'Monday, Friday, Tuesday'),
('Slavica Kassidy', 'Freshman','Novice', 'Monday, Sunday, Saturday'),
('Alison Pond', 'Senior','Novice', 'Wednesday, Friday, Tuesday'),
('Guanting Dympna', 'Sophomore','Novice', 'Wednesday, Saturday, Sunday'),
('Yasaman Shqipe', 'Freshman',"Expert", 'Wednesday, Saturday, Tuesday'),
('Huw Mahnaz', 'Freshman','Beginner', 'Monday Wednesday, Friday'),
('Hedwig Damiana', 'Sophomore','Novice', 'Saturday, Wednesday, Friday'),
('Emily Gennadi', 'Sophomore','Novice', 'Wednesday, Saturday, Sunday'),
('Marielle Steph', 'Sophomore',"Expert", 'Saturday, Thursday, Friday'),
('Reinaldo Kay', 'Freshman','Beginner', 'Monday, Thursday, Friday')
;

CREATE table games (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    person_id INTEGER,
    game TEXT);
    
INSERT INTO games (
    person_id, 
    game
    )
      

VALUES

(1, 'D&D'),
(2, 'Pathfinder'),
(3, 'Ryuutama'),
(4, 'D&D'),
(5, 'Lancer'),
(6, 'D&D'),
(7, 'Cyperpunk'),
(8, 'D&D'),
(9, 'Lancer'),
(10, 'Pathfinder'),
(11, 'D&D'),
(12, 'Lancer'),
(13, 'D&D'),
(14, 'D&D'),
(15, 'D&D'),
(16, 'Pathfinder'),
(17, 'D&D'),
(18, 'D&D'),
(19, 'Lancer'),
(20, 'D&D'),
(21, 'D&D'),
(22, 'Pathfinder'),
(23, 'Pathfinder'),
(24, 'Cyperpunk'),
(25, 'Cyperpunk'),
(26, 'D&D'),
(27, 'Lancer'),
(28, 'Ryuutama'),
(29, 'Pathfinder'),
(30, 'D&D'),
(31, 'Lancer'),
(32, 'Lancer'),
(33, 'Pathfinder'),
(34, 'D&D'),
(35, 'Pathfinder'),
(36, 'Lancer'),
(37, 'Pathfinder'),
(38, 'Pathfinder'),
(39, 'D&D'),
(40, 'D&D'),
(41, 'D&D'),
(42, 'D&D'),
(43, 'Lancer'),
(44, 'Lancer'),
(45, 'D&D'),
(46, 'Ryuutama'),
(47, 'Ryuutama'),
(48, 'Lancer'),
(49, 'Pathfinder'),
(50, 'Ryuutama'),
(51, 'Pathfinder'),
(52, 'D&D'),
(53, 'Lancer'),
(54, 'Cyperpunk'),
(55, 'D&D'),
(56, 'Cyperpunk'),
(57, 'Cyperpunk'),
(58, 'D&D'),
(59, 'D&D'),
(60, 'Ryuutama');


CREATE table schedules (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    dm_id INTEGER,
    player_id INTEGER,
    day_playing TEXT);
    
INSERT INTO schedules (
    dm_id,
    player_id,
    day_playing
    )

VALUES 

(1, 14 ,  'Friday'),

(1,15 ,  'Friday'),

(1,17 ,  'Friday'),
(1,13 ,  'Friday'),
(1,20 ,  'Friday'),
(2,16 ,  'Friday'),
(2,22 ,  'Friday'),
(2,23 ,  'Friday'),
(2,29 ,  'Friday'),
(2,33 ,  'Friday'),
(3,28 ,  'Thursday'),
(3,46 ,  'Thursday'),
(3,47 ,  'Thursday'),
(3,50 ,  'Thursday'),
(3,60 ,  'Thursday'),
(4,21 ,  'Saturday'),
(4,26 ,  'Saturday'),
(4,30 ,  'Saturday'),
(4,34 ,  'Saturday'),
(4,39 ,  'Saturday'),
(5,12 ,  'Monday'),
(5,27 ,  'Monday'),
(5,31 ,  'Monday'),
(5,32 ,  'Monday'),
(5,43 ,  'Monday'),
(6,40 ,  'Sunday'),
(6,41 ,  'Sunday'),
(6,42 ,  'Sunday'),
(6,45 ,  'Sunday'),
(6,52 ,  'Sunday'),
(7,24 ,  'Wednesday'),
(7,25 ,  'Wednesday'),
(7,54 ,  'Wednesday'),
(7,56 ,  ' Wednesday'),
(7,57 ,  ' Wednesday'),
(8,11 ,  'Saturday'),
(8,55 ,  'Saturday'),
(8,58 ,  'Saturday'),
(8,59 ,  'Saturday'),
(8,18 ,  'Saturday'),
(9,19 ,  'Tuesday'),
(9,36 ,  'Tuesday'),
(9,44 ,  'Tuesday'),
(9,48 ,  'Tuesday'),
(9,53 ,  'Tuesday'),
(10,35 ,  'Friday'),
(10,37 ,  'Friday'),
(10,38 ,  'Friday'),
(10,49 ,  'Friday'),
(10,51 ,  'Friday');





